version: '3.8'
services:
  db:
    image: postgres:15
    container_name: tone_engine_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tank
      - POSTGRES_DB=ToneEngine
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: tone_engine_app_ver1
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=ToneEngine
      - DB_USER=postgres
      - DB_PASS=tank
    depends_on:
      - db
volumes:
  pg_data:
